version: 1

providers:
  oci:
    auth:
      mode: config_file
      region: us-phoenix-1
      config_file: ~/.oci/config
      profile: DEFAULT

    locations:
      dev3top:
        compartment_id: ocid1.compartment.oc1...
        vault_id: ocid1.vault.oc1...
        secret_name_template: "{var}"
